{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\tqdm\\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "\n",
    "sys.path.append(\"../\")\n",
    "\n",
    "import os\n",
    "import torch\n",
    "import matplotlib\n",
    "import matplotlib.pyplot as plt\n",
    "from src.utils.parser import get_config\n",
    "from src.datasets.dhf1k_dataset import DHF1KDataModule\n",
    "from src.lightning_models.lightning_model import LightningModel\n",
    "\n",
    "matplotlib.use(\"TkAgg\")\n",
    "os.environ[\"KMP_DUPLICATE_LIB_OK\"] = \"True\"\n",
    "\n",
    "from src.models.vidas import ViDaS\n",
    "from src.utils.file import get_paths_recursive\n",
    "from src.config import (\n",
    "    SEED,\n",
    "    DEVICE,\n",
    "    N_WORKERS,\n",
    "    CONFIG_PATH,\n",
    "    MODELS_PATH,\n",
    "    SEQUENCE_LENGTH,\n",
    "    PROCESSED_DHF1K_PATH,\n",
    ")\n",
    "\n",
    "STATE_FILE_PATH = f\"{MODELS_PATH}/vidas/20241130-144816_vidas/epoch=9-val_loss=0.49.ckpt\"\n",
    "CONFIG_FILE_PATH = f\"{CONFIG_PATH}/vidas/default.yml\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Get config parameters\n",
    "config = get_config(CONFIG_FILE_PATH)\n",
    "n_epochs = int(config[\"n_epochs\"])\n",
    "learning_rate = float(config[\"learning_rate\"])\n",
    "weight_decay = float(config[\"weight_decay\"])\n",
    "evaluation_steps = int(config[\"evaluation_steps\"])\n",
    "splits = tuple(map(float, config[\"splits\"]))\n",
    "save_model = bool(config[\"save_model\"])\n",
    "with_transforms = bool(config[\"with_transforms\"])\n",
    "input_channels = int(config[\"input_channels\"])\n",
    "hidden_channels_list = list(map(int, config[\"hidden_channels_list\"]))\n",
    "kernel_sizes = list(map(int, config[\"kernel_sizes\"]))\n",
    "use_max_poolings = list(map(bool, config[\"use_max_poolings\"]))\n",
    "saliency_out_channels = int(config[\"saliency_out_channels\"])\n",
    "attention_out_channels = int(config[\"attention_out_channels\"])\n",
    "with_depth_information = bool(config[\"with_depth_information\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Seed set to 0\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ðŸŒ± Setting the seed to 0 for generating dataloaders.\n"
     ]
    }
   ],
   "source": [
    "sample_folder_paths = get_paths_recursive(\n",
    "    folder_path=PROCESSED_DHF1K_PATH, match_pattern=\"*\", path_type=\"d\"\n",
    ")\n",
    "data_module = DHF1KDataModule(\n",
    "    sample_folder_paths=sample_folder_paths,\n",
    "    batch_size=1,\n",
    "    train_splits=splits[0],\n",
    "    val_splits=splits[1],\n",
    "    test_splits=splits[2],\n",
    "    with_transforms=with_transforms,\n",
    "    n_workers=N_WORKERS,\n",
    "    seed=SEED,\n",
    ")\n",
    "data_module.setup(\"test\")\n",
    "test_loader = data_module.test_dataloader()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "model = ViDaS(\n",
    "    input_channels=input_channels,\n",
    "    hidden_channels_list=hidden_channels_list,\n",
    "    kernel_sizes=kernel_sizes,\n",
    "    use_max_poolings=use_max_poolings,\n",
    "    saliency_out_channels=saliency_out_channels,\n",
    "    attention_out_channels=attention_out_channels,\n",
    "    with_depth_information=with_depth_information,\n",
    ")\n",
    "lightning_model = LightningModel.load_from_checkpoint(\n",
    "    checkpoint_path=STATE_FILE_PATH,\n",
    "    model=model,\n",
    "    learning_rate=learning_rate,\n",
    "    weight_decay=weight_decay,\n",
    "    name=\"vidas\",\n",
    "    dataset=\"dhf1k\",\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\tkinter\\__init__.py\", line 861, in callit\n",
      "    func(*args)\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 142, in _on_timer\n",
      "    super()._on_timer()\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\backend_bases.py\", line 1179, in _on_timer\n",
      "    ret = func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\animation.py\", line 1407, in _step\n",
      "    still_going = super()._step(*args)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\animation.py\", line 1101, in _step\n",
      "    self._draw_next_frame(framedata, self._blit)\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\animation.py\", line 1120, in _draw_next_frame\n",
      "    self._draw_frame(framedata)\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\animation.py\", line 1746, in _draw_frame\n",
      "    self._drawn_artists = self._func(framedata, *self._args)\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arnau\\AppData\\Local\\Temp\\ipykernel_23540\\1908634039.py\", line 53, in animate\n",
      "    output_frame = output[0, frame_idx]\n",
      "                   ~~~~~~^^^^^^^^^^^^^^\n",
      "IndexError: index 1 is out of bounds for dimension 1 with size 1\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\tkinter\\__init__.py\", line 861, in callit\n",
      "    func(*args)\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 142, in _on_timer\n",
      "    super()._on_timer()\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\backend_bases.py\", line 1179, in _on_timer\n",
      "    ret = func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\animation.py\", line 1407, in _step\n",
      "    still_going = super()._step(*args)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\animation.py\", line 1101, in _step\n",
      "    self._draw_next_frame(framedata, self._blit)\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\animation.py\", line 1120, in _draw_next_frame\n",
      "    self._draw_frame(framedata)\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\animation.py\", line 1746, in _draw_frame\n",
      "    self._drawn_artists = self._func(framedata, *self._args)\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arnau\\AppData\\Local\\Temp\\ipykernel_23540\\1908634039.py\", line 53, in animate\n",
      "    output_frame = output[0, frame_idx]\n",
      "                   ~~~~~~^^^^^^^^^^^^^^\n",
      "IndexError: index 1 is out of bounds for dimension 1 with size 1\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\tkinter\\__init__.py\", line 861, in callit\n",
      "    func(*args)\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 142, in _on_timer\n",
      "    super()._on_timer()\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\backend_bases.py\", line 1179, in _on_timer\n",
      "    ret = func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\animation.py\", line 1407, in _step\n",
      "    still_going = super()._step(*args)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\animation.py\", line 1101, in _step\n",
      "    self._draw_next_frame(framedata, self._blit)\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\animation.py\", line 1120, in _draw_next_frame\n",
      "    self._draw_frame(framedata)\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\animation.py\", line 1746, in _draw_frame\n",
      "    self._drawn_artists = self._func(framedata, *self._args)\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arnau\\AppData\\Local\\Temp\\ipykernel_23540\\1908634039.py\", line 53, in animate\n",
      "    output_frame = output[0, frame_idx]\n",
      "                   ~~~~~~^^^^^^^^^^^^^^\n",
      "IndexError: index 1 is out of bounds for dimension 1 with size 1\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\tkinter\\__init__.py\", line 861, in callit\n",
      "    func(*args)\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 142, in _on_timer\n",
      "    super()._on_timer()\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\backend_bases.py\", line 1179, in _on_timer\n",
      "    ret = func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\animation.py\", line 1407, in _step\n",
      "    still_going = super()._step(*args)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\animation.py\", line 1101, in _step\n",
      "    self._draw_next_frame(framedata, self._blit)\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\animation.py\", line 1120, in _draw_next_frame\n",
      "    self._draw_frame(framedata)\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\animation.py\", line 1746, in _draw_frame\n",
      "    self._drawn_artists = self._func(framedata, *self._args)\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arnau\\AppData\\Local\\Temp\\ipykernel_23540\\1908634039.py\", line 53, in animate\n",
      "    output_frame = output[0, frame_idx]\n",
      "                   ~~~~~~^^^^^^^^^^^^^^\n",
      "IndexError: index 1 is out of bounds for dimension 1 with size 1\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\tkinter\\__init__.py\", line 861, in callit\n",
      "    func(*args)\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 142, in _on_timer\n",
      "    super()._on_timer()\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\backend_bases.py\", line 1179, in _on_timer\n",
      "    ret = func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\animation.py\", line 1407, in _step\n",
      "    still_going = super()._step(*args)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\animation.py\", line 1101, in _step\n",
      "    self._draw_next_frame(framedata, self._blit)\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\animation.py\", line 1120, in _draw_next_frame\n",
      "    self._draw_frame(framedata)\n",
      "  File \"c:\\Users\\arnau\\anaconda3\\envs\\pdm\\Lib\\site-packages\\matplotlib\\animation.py\", line 1746, in _draw_frame\n",
      "    self._drawn_artists = self._func(framedata, *self._args)\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arnau\\AppData\\Local\\Temp\\ipykernel_23540\\1908634039.py\", line 53, in animate\n",
      "    output_frame = output[0, frame_idx]\n",
      "                   ~~~~~~^^^^^^^^^^^^^^\n",
      "IndexError: index 1 is out of bounds for dimension 1 with size 1\n"
     ]
    }
   ],
   "source": [
    "from matplotlib.widgets import Button\n",
    "from matplotlib.animation import FuncAnimation\n",
    "\n",
    "def visualize_batches(lightning_model, dataloader, interval=500):\n",
    "    lightning_model.eval()\n",
    "    lightning_model = lightning_model.to(DEVICE)\n",
    "    \n",
    "    # Create iterator\n",
    "    dataloader_iter = iter(dataloader)\n",
    "    \n",
    "    # Create figure and axes\n",
    "    fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(20, 10))\n",
    "    plt.subplots_adjust(bottom=0.2)  # Make room for button\n",
    "    \n",
    "    # Global variables to store current batch data\n",
    "    current_batch = None\n",
    "    anim = None\n",
    "    \n",
    "    def process_batch():\n",
    "        frame, ground_truths, global_ground_truth = next(dataloader_iter)\n",
    "        input = frame.to(DEVICE)\n",
    "        with torch.no_grad():\n",
    "            _, output = lightning_model.model(input.float())\n",
    "\n",
    "        if output.dim() == 3:\n",
    "            output = output.unsqueeze(1)\n",
    "\n",
    "        if output.shape[1] == 1:\n",
    "            ground_truth = global_ground_truth.unsqueeze(1).to(DEVICE)\n",
    "        else:\n",
    "            ground_truth = ground_truths.to(DEVICE)\n",
    "        \n",
    "        return input, output, ground_truth\n",
    "    \n",
    "    def init_animation():\n",
    "        ax1.clear()\n",
    "        ax2.clear()\n",
    "        ax3.clear()\n",
    "        return ax1, ax2, ax3\n",
    "\n",
    "    def animate(frame_idx):\n",
    "        ax1.clear()\n",
    "        ax2.clear()\n",
    "        ax3.clear()\n",
    "        \n",
    "        input, output, ground_truths = current_batch\n",
    "        \n",
    "        # Get the first sample of the sequence for the current frame\n",
    "        if input.dim() == 4:\n",
    "            input_frame = input[0]\n",
    "        elif input.dim() == 5:\n",
    "            input_frame = input[0, frame_idx]\n",
    "        output_frame = output[0, frame_idx]\n",
    "        gt_frame = ground_truths[0, frame_idx]\n",
    "        \n",
    "        # Process input frame for visualization\n",
    "        input_np = input_frame.permute(1, 2, 0).cpu().detach().numpy()\n",
    "        \n",
    "        # Process output and ground truth\n",
    "        output_np = output_frame.cpu().detach().numpy()\n",
    "        gt_np = gt_frame.cpu().detach().numpy()\n",
    "        \n",
    "        # Display frames\n",
    "        ax1.imshow(input_np)\n",
    "        ax2.imshow(output_np, cmap=\"jet\", vmin=0, vmax=1)\n",
    "        ax3.imshow(gt_np, cmap=\"jet\", vmin=0, vmax=1)\n",
    "        \n",
    "        ax1.set_title(f'Input (Sequence {frame_idx + 1}/3)')\n",
    "        ax2.set_title(f'Output (Sequence {frame_idx + 1}/3)')\n",
    "        ax3.set_title(f'Ground Truth (Sequence {frame_idx + 1}/3)')\n",
    "        ax1.axis('off')\n",
    "        ax2.axis('off')\n",
    "        ax3.axis('off')\n",
    "        \n",
    "        return ax1, ax2, ax3\n",
    "    \n",
    "    def update_plot(event=None):\n",
    "        nonlocal current_batch, anim\n",
    "        \n",
    "        try:\n",
    "            # Get new batch\n",
    "            current_batch = process_batch()\n",
    "            \n",
    "            # If there's an existing animation, stop it\n",
    "            if anim is not None:\n",
    "                anim.event_source.stop()\n",
    "            \n",
    "            # Create new animation\n",
    "            anim = FuncAnimation(\n",
    "                fig, \n",
    "                animate, \n",
    "                init_func=init_animation,\n",
    "                frames=SEQUENCE_LENGTH,\n",
    "                interval=interval,\n",
    "                repeat=True,\n",
    "                blit=True\n",
    "            )\n",
    "            \n",
    "        except StopIteration:\n",
    "            print(\"Reached the end of the dataset. Restarting...\")\n",
    "            nonlocal dataloader_iter\n",
    "            dataloader_iter = iter(dataloader)\n",
    "            update_plot()\n",
    "        \n",
    "        fig.canvas.draw_idle()\n",
    "    \n",
    "    # Add button\n",
    "    ax_button = plt.axes([0.4, 0.05, 0.2, 0.075])\n",
    "    button = Button(ax_button, 'Next Batch')\n",
    "    button.on_clicked(update_plot)\n",
    "    \n",
    "    # Show initial batch\n",
    "    update_plot()\n",
    "    \n",
    "    plt.show(block=True)\n",
    "\n",
    "visualize_batches(lightning_model, test_loader, interval=500)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "pdm",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
